# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenJio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenJio

pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  
  pod 'SwiftIconFont'

  pod 'Eureka', '~> 2.0.0-beta.1'
end
